services:
  postgres:
    image: postgres:17.8-bookworm
    command: "-d 1"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    env_file:
      - .env.local
    volumes:
      - localstack_data:/var/lib/localstack
      - ./docker/localstack-init:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD", "test", "-f", "/var/lib/localstack/localstack_ready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

volumes:
  db_data:
  localstack_data:
