export interface FamilyMember {
  id: string;
  name: string;
  relationship: string;
  generation: number; // -3: great grandparents, -2: grandparents, -1: parents, 0: current generation, 1: children, 2: grandchildren
  birthYear?: number;
  location?: string;
  occupation?: string;
  spouse?: string;
  children?: string[];
  bio?: string;
}

export const familyData: FamilyMember[] = [
  // Great Grandparents (Generation -3)
  {
    id: "1",
    name: "William Smith",
    relationship: "Great Grandfather",
    generation: -3,
    birthYear: 1920,
    location: "Boston, MA",
    occupation: "Railroad Engineer",
    spouse: "Margaret Smith",
    children: ["James Smith", "Thomas Smith", "Catherine Brown"],
  },
  {
    id: "2",
    name: "Margaret Smith",
    relationship: "Great Grandmother",
    generation: -3,
    birthYear: 1925,
    location: "Boston, MA",
    occupation: "School Teacher",
    spouse: "William Smith",
    children: ["James Smith", "Thomas Smith", "Catherine Brown"],
  },
  {
    id: "3",
    name: "Robert Johnson",
    relationship: "Great Grandfather",
    generation: -3,
    birthYear: 1918,
    location: "Chicago, IL",
    occupation: "Factory Foreman",
    spouse: "Helen Johnson",
    children: ["Michael Johnson", "Patricia Smith"],
  },
  {
    id: "4",
    name: "Helen Johnson",
    relationship: "Great Grandmother",
    generation: -3,
    birthYear: 1922,
    location: "Chicago, IL",
    occupation: "Seamstress",
    spouse: "Robert Johnson",
    children: ["Michael Johnson", "Patricia Smith"],
  },
  {
    id: "39",
    name: "Charles Davis",
    relationship: "Great Grandfather",
    generation: -3,
    birthYear: 1915,
    location: "Detroit, MI",
    occupation: "Auto Worker",
    spouse: "Rose Davis",
    children: ["Linda Johnson"],
  },
  {
    id: "40",
    name: "Rose Davis",
    relationship: "Great Grandmother",
    generation: -3,
    birthYear: 1920,
    location: "Detroit, MI",
    occupation: "Homemaker",
    spouse: "Charles Davis",
    children: ["Linda Johnson"],
  },

  // Grandparents (Generation -2)
  {
    id: "5",
    name: "James Smith",
    relationship: "Grandfather",
    generation: -2,
    birthYear: 1945,
    location: "New York, NY",
    occupation: "Accountant",
    spouse: "Patricia Smith",
    children: ["David Smith", "Susan Miller", "Robert Smith"],
  },
  {
    id: "6",
    name: "Patricia Smith",
    relationship: "Grandmother",
    generation: -2,
    birthYear: 1948,
    location: "New York, NY",
    occupation: "Nurse",
    spouse: "James Smith",
    children: ["David Smith", "Susan Miller", "Robert Smith"],
  },
  {
    id: "7",
    name: "Michael Johnson",
    relationship: "Grandfather",
    generation: -2,
    birthYear: 1943,
    location: "Philadelphia, PA",
    occupation: "Police Officer",
    spouse: "Linda Johnson",
    children: ["Sarah Smith", "Karen Wilson"],
  },
  {
    id: "8",
    name: "Linda Johnson",
    relationship: "Grandmother",
    generation: -2,
    birthYear: 1946,
    location: "Philadelphia, PA",
    occupation: "Librarian",
    spouse: "Michael Johnson",
    children: ["Sarah Smith", "Karen Wilson"],
  },
  {
    id: "21",
    name: "Thomas Smith",
    relationship: "Great Uncle",
    generation: -2,
    birthYear: 1947,
    location: "Seattle, WA",
    occupation: "Architect",
    spouse: "Maria Smith",
    children: ["Daniel Smith", "Lisa Garcia"],
  },
  {
    id: "22",
    name: "Maria Smith",
    relationship: "Great Aunt",
    generation: -2,
    birthYear: 1950,
    location: "Seattle, WA",
    occupation: "Interior Designer",
    spouse: "Thomas Smith",
    children: ["Daniel Smith", "Lisa Garcia"],
  },
  {
    id: "23",
    name: "Catherine Brown",
    relationship: "Great Aunt",
    generation: -2,
    birthYear: 1949,
    location: "Portland, OR",
    occupation: "Teacher",
    spouse: "Frank Brown",
    children: ["Michelle Brown", "Steven Brown"],
  },
  {
    id: "24",
    name: "Frank Brown",
    relationship: "Great Uncle",
    generation: -2,
    birthYear: 1946,
    location: "Portland, OR",
    occupation: "Engineer",
    spouse: "Catherine Brown",
    children: ["Michelle Brown", "Steven Brown"],
  },

  // Parents Generation (Generation -1)
  {
    id: "9",
    name: "David Smith",
    relationship: "Father",
    generation: -1,
    birthYear: 1970,
    location: "San Francisco, CA",
    occupation: "Software Engineer",
    spouse: "Sarah Smith",
    children: ["John Smith", "Jennifer Smith", "Michael Smith"],
  },
  {
    id: "10",
    name: "Sarah Smith",
    relationship: "Mother",
    generation: -1,
    birthYear: 1972,
    location: "San Francisco, CA",
    occupation: "Marketing Director",
    spouse: "David Smith",
    children: ["John Smith", "Jennifer Smith", "Michael Smith"],
  },

  // Current Generation (Generation 0) - John Smith and siblings
  {
    id: "11",
    name: "John Smith",
    relationship: "Self",
    generation: 0,
    birthYear: 1995,
    location: "San Francisco, CA",
    occupation: "Product Manager",
    spouse: "Emily Smith",
    children: ["Oliver Smith", "Emma Smith"],
  },
  {
    id: "12",
    name: "Emily Smith",
    relationship: "Spouse",
    generation: 0,
    birthYear: 1997,
    location: "San Francisco, CA",
    occupation: "Graphic Designer",
    spouse: "John Smith",
    children: ["Oliver Smith", "Emma Smith"],
  },
  {
    id: "13",
    name: "Jennifer Smith",
    relationship: "Sister",
    generation: 0,
    birthYear: 1993,
    location: "Los Angeles, CA",
    occupation: "Doctor",
    spouse: "Mark Wilson",
    children: ["Sophia Wilson", "Lucas Wilson"],
  },
  {
    id: "14",
    name: "Mark Wilson",
    relationship: "Brother-in-law",
    generation: 0,
    birthYear: 1991,
    location: "Los Angeles, CA",
    occupation: "Lawyer",
    spouse: "Jennifer Smith",
    children: ["Sophia Wilson", "Lucas Wilson"],
  },
  {
    id: "25",
    name: "Michael Smith",
    relationship: "Brother",
    generation: 0,
    birthYear: 1998,
    location: "Austin, TX",
    occupation: "Software Developer",
    spouse: "Amanda Smith",
    children: ["Jacob Smith"],
  },
  {
    id: "26",
    name: "Amanda Smith",
    relationship: "Sister-in-law",
    generation: 0,
    birthYear: 1999,
    location: "Austin, TX",
    occupation: "UX Designer",
    spouse: "Michael Smith",
    children: ["Jacob Smith"],
  },

  // Aunts and Uncles (Generation -1)
  {
    id: "27",
    name: "Robert Smith",
    relationship: "Uncle",
    generation: -1,
    birthYear: 1968,
    location: "Denver, CO",
    occupation: "Construction Manager",
    spouse: "Nancy Smith",
    children: ["Kevin Smith", "Rachel Smith"],
  },
  {
    id: "28",
    name: "Nancy Smith",
    relationship: "Aunt",
    generation: -1,
    birthYear: 1971,
    location: "Denver, CO",
    occupation: "Real Estate Agent",
    spouse: "Robert Smith",
    children: ["Kevin Smith", "Rachel Smith"],
  },
  {
    id: "29",
    name: "Susan Miller",
    relationship: "Aunt",
    generation: -1,
    birthYear: 1973,
    location: "Miami, FL",
    occupation: "Pharmacist",
    spouse: "Paul Miller",
    children: ["Ashley Miller", "Brandon Miller"],
  },
  {
    id: "30",
    name: "Paul Miller",
    relationship: "Uncle",
    generation: -1,
    birthYear: 1970,
    location: "Miami, FL",
    occupation: "Business Owner",
    spouse: "Susan Miller",
    children: ["Ashley Miller", "Brandon Miller"],
  },
  {
    id: "31",
    name: "Karen Wilson",
    relationship: "Aunt",
    generation: -1,
    birthYear: 1975,
    location: "Phoenix, AZ",
    occupation: "Veterinarian",
    spouse: "James Wilson",
    children: ["Tyler Wilson", "Megan Wilson"],
  },
  {
    id: "32",
    name: "James Wilson",
    relationship: "Uncle",
    generation: -1,
    birthYear: 1972,
    location: "Phoenix, AZ",
    occupation: "Electrician",
    spouse: "Karen Wilson",
    children: ["Tyler Wilson", "Megan Wilson"],
  },

  // Cousins (Generation 0)
  {
    id: "33",
    name: "Daniel Smith",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1994,
    location: "Seattle, WA",
    occupation: "Teacher",
    spouse: "Jessica Smith",
    children: ["Noah Smith"],
  },
  {
    id: "34",
    name: "Jessica Smith",
    relationship: "Cousin-in-law",
    generation: 0,
    birthYear: 1996,
    location: "Seattle, WA",
    occupation: "Nurse",
    spouse: "Daniel Smith",
    children: ["Noah Smith"],
  },
  {
    id: "35",
    name: "Lisa Garcia",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1992,
    location: "San Diego, CA",
    occupation: "Marketing Manager",
    spouse: "Carlos Garcia",
    children: ["Isabella Garcia"],
  },
  {
    id: "36",
    name: "Carlos Garcia",
    relationship: "Cousin-in-law",
    generation: 0,
    birthYear: 1990,
    location: "San Diego, CA",
    occupation: "Chef",
    spouse: "Lisa Garcia",
    children: ["Isabella Garcia"],
  },

  // Children (Generation 1)
  {
    id: "15",
    name: "Oliver Smith",
    relationship: "Son",
    generation: 1,
    birthYear: 2020,
    location: "San Francisco, CA",
  },
  {
    id: "37",
    name: "Emma Smith",
    relationship: "Daughter",
    generation: 1,
    birthYear: 2022,
    location: "San Francisco, CA",
  },
  {
    id: "16",
    name: "Sophia Wilson",
    relationship: "Niece",
    generation: 1,
    birthYear: 2018,
    location: "Los Angeles, CA",
  },
  {
    id: "17",
    name: "Lucas Wilson",
    relationship: "Nephew",
    generation: 1,
    birthYear: 2021,
    location: "Los Angeles, CA",
  },
  {
    id: "38",
    name: "Jacob Smith",
    relationship: "Nephew",
    generation: 1,
    birthYear: 2023,
    location: "Austin, TX",
  },
  {
    id: "18",
    name: "Kevin Smith",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1996,
    location: "Denver, CO",
  },
  {
    id: "19",
    name: "Rachel Smith",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1998,
    location: "Denver, CO",
  },
  {
    id: "20",
    name: "Ashley Miller",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1994,
    location: "Miami, FL",
  },
  {
    id: "41",
    name: "Brandon Miller",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1997,
    location: "Miami, FL",
  },
  {
    id: "42",
    name: "Tyler Wilson",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1993,
    location: "Phoenix, AZ",
  },
  {
    id: "43",
    name: "Megan Wilson",
    relationship: "Cousin",
    generation: 0,
    birthYear: 1995,
    location: "Phoenix, AZ",
  },
  {
    id: "44",
    name: "Noah Smith",
    relationship: "Second Cousin",
    generation: 1,
    birthYear: 2020,
    location: "Seattle, WA",
  },
  {
    id: "45",
    name: "Isabella Garcia",
    relationship: "Second Cousin",
    generation: 1,
    birthYear: 2019,
    location: "San Diego, CA",
  },
];
